import { BusinessOperationsData } from './types';

const brewedAwakeningOps: BusinessOperationsData = {
  businessId: 'biz-001',
  areas: [
    {
      id: 'area-001-1',
      name: 'Front of House',
      description: 'Customer-facing service, seating, and order flow',
      status: 'healthy',
      owner: 'Jordan Lee',
    },
    {
      id: 'area-001-2',
      name: 'Kitchen & Food Prep',
      description: 'Espresso, food preparation, and equipment management',
      status: 'at_risk',
      owner: 'Jordan Lee',
    },
    {
      id: 'area-001-3',
      name: 'Inventory & Supply',
      description: 'Stock levels, ordering, and supplier coordination',
      status: 'healthy',
      owner: 'Sam Rivera',
    },
    {
      id: 'area-001-4',
      name: 'Staffing & Scheduling',
      description: 'Team shifts, coverage, and HR coordination',
      status: 'at_risk',
      owner: 'Jordan Lee',
    },
    {
      id: 'area-001-5',
      name: 'Finance Admin',
      description: 'Daily reconciliation, invoices, and payroll prep',
      status: 'healthy',
      owner: 'Taylor Brooks',
    },
  ],
  recurringTasks: [
    {
      id: 'task-001-1',
      title: 'Daily Opening Checklist',
      description: 'Verify equipment, clean stations, prepare opening stock, open registers',
      frequency: 'daily',
      status: 'pending',
      nextDue: 'Today',
      areaId: 'area-001-1',
      owner: 'Jordan Lee',
    },
    {
      id: 'task-001-2',
      title: 'Cash Reconciliation',
      description: 'End-of-day cash count, POS reconciliation, and deposit prep',
      frequency: 'daily',
      status: 'pending',
      nextDue: 'Today',
      areaId: 'area-001-5',
      owner: 'Taylor Brooks',
    },
    {
      id: 'task-001-3',
      title: 'Weekly Stock Check',
      description: 'Count all coffee, dairy, food, and packaging inventory',
      frequency: 'weekly',
      status: 'in_progress',
      nextDue: 'Today',
      areaId: 'area-001-3',
      owner: 'Sam Rivera',
    },
    {
      id: 'task-001-4',
      title: 'Supplier Order Review',
      description: 'Review stock levels and place orders with coffee and food suppliers',
      frequency: 'weekly',
      status: 'pending',
      nextDue: 'This Week',
      areaId: 'area-001-3',
      owner: 'Sam Rivera',
    },
    {
      id: 'task-001-5',
      title: 'Equipment Inspection',
      description: 'Inspect espresso machines, grinders, and refrigeration units',
      frequency: 'biweekly',
      status: 'overdue',
      nextDue: 'Overdue',
      areaId: 'area-001-2',
      owner: 'Jordan Lee',
    },
    {
      id: 'task-001-6',
      title: 'Staff Scheduling Review',
      description: "Build and confirm next week's shift schedule with team",
      frequency: 'weekly',
      status: 'pending',
      nextDue: 'This Week',
      areaId: 'area-001-4',
      owner: 'Jordan Lee',
    },
    {
      id: 'task-001-7',
      title: 'Payroll Preparation',
      description: 'Collect hours, calculate wages, submit payroll run',
      frequency: 'monthly',
      status: 'pending',
      nextDue: 'This Month',
      areaId: 'area-001-5',
      owner: 'Taylor Brooks',
    },
    {
      id: 'task-001-8',
      title: 'Cleaning Verification',
      description: 'Verify deep-clean completion for kitchen and front areas',
      frequency: 'daily',
      status: 'completed',
      nextDue: 'Today',
      areaId: 'area-001-1',
      owner: 'Jordan Lee',
    },
  ],
  issues: [
    {
      id: 'issue-001-1',
      title: 'Espresso Machine Maintenance Overdue',
      description: 'Primary espresso machine is past its scheduled service window. Risk of breakdowns during peak hours.',
      severity: 'high',
      status: 'open',
      areaId: 'area-001-2',
      owner: 'Jordan Lee',
      createdAt: '2024-03-01T10:00:00Z',
    },
    {
      id: 'issue-001-2',
      title: 'Weekend Staffing Gap',
      description: 'Two baristas unavailable on Saturdays for next 3 weeks. Potential service slowdowns during peak hours.',
      severity: 'high',
      status: 'in_progress',
      areaId: 'area-001-4',
      owner: 'Jordan Lee',
      createdAt: '2024-03-03T09:00:00Z',
    },
    {
      id: 'issue-001-3',
      title: 'Milk Supplier Price Increase',
      description: 'Primary dairy supplier notified 12% price increase effective next month. Need to evaluate alternatives.',
      severity: 'medium',
      status: 'open',
      areaId: 'area-001-3',
      owner: 'Sam Rivera',
      createdAt: '2024-03-05T14:00:00Z',
    },
  ],
};

const apexThreadsOps: BusinessOperationsData = {
  businessId: 'biz-002',
  areas: [
    {
      id: 'area-002-1',
      name: 'In-Store Sales',
      description: 'Floor operations, customer service, and daily sales performance',
      status: 'healthy',
      owner: 'Chris Nguyen',
    },
    {
      id: 'area-002-2',
      name: 'Inventory Management',
      description: 'Stock tracking, reordering, and product availability',
      status: 'at_risk',
      owner: 'Dana Kim',
    },
    {
      id: 'area-002-3',
      name: 'Online Store',
      description: 'E-commerce operations, listings, and order fulfillment',
      status: 'healthy',
      owner: 'Chris Nguyen',
    },
    {
      id: 'area-002-4',
      name: 'Supplier Relations',
      description: 'Vendor management, procurement, and supply chain coordination',
      status: 'critical',
      owner: 'Chris Nguyen',
    },
    {
      id: 'area-002-5',
      name: 'Finance Admin',
      description: 'Sales tracking, expense management, and bookkeeping',
      status: 'healthy',
      owner: 'Chris Nguyen',
    },
  ],
  recurringTasks: [
    {
      id: 'task-002-1',
      title: 'Daily Sales Review',
      description: 'Review in-store and online sales figures against targets',
      frequency: 'daily',
      status: 'completed',
      nextDue: 'Today',
      areaId: 'area-002-1',
      owner: 'Chris Nguyen',
    },
    {
      id: 'task-002-2',
      title: 'Weekly Inventory Count',
      description: 'Full stock count across all product categories and size variants',
      frequency: 'weekly',
      status: 'overdue',
      nextDue: 'Overdue',
      areaId: 'area-002-2',
      owner: 'Dana Kim',
    },
    {
      id: 'task-002-3',
      title: 'Reorder Fast-Moving Items',
      description: 'Identify and reorder items below minimum stock threshold',
      frequency: 'weekly',
      status: 'pending',
      nextDue: 'This Week',
      areaId: 'area-002-2',
      owner: 'Dana Kim',
    },
    {
      id: 'task-002-4',
      title: 'Supplier Follow-ups',
      description: 'Check delivery status, confirm upcoming orders, resolve disputes',
      frequency: 'biweekly',
      status: 'in_progress',
      nextDue: 'Today',
      areaId: 'area-002-4',
      owner: 'Chris Nguyen',
    },
    {
      id: 'task-002-5',
      title: 'Online Listings Review',
      description: 'Update product availability, pricing, and photos on the online store',
      frequency: 'weekly',
      status: 'pending',
      nextDue: 'This Week',
      areaId: 'area-002-3',
      owner: 'Chris Nguyen',
    },
    {
      id: 'task-002-6',
      title: 'Monthly Financial Review',
      description: 'Reconcile expenses, review P&L, update budget tracking',
      frequency: 'monthly',
      status: 'pending',
      nextDue: 'This Month',
      areaId: 'area-002-5',
      owner: 'Chris Nguyen',
    },
  ],
  issues: [
    {
      id: 'issue-002-1',
      title: 'Key Supplier Shipment Delayed 3 Weeks',
      description: 'Primary clothing supplier delayed spring collection by 3 weeks. Bestsellers running low in-store and online.',
      severity: 'critical',
      status: 'open',
      areaId: 'area-002-4',
      owner: 'Chris Nguyen',
      createdAt: '2024-03-04T10:00:00Z',
    },
    {
      id: 'issue-002-2',
      title: 'Low Stock on Bestselling Lines',
      description: 'Three top-selling product lines at 15% or below minimum stock. Revenue impact already visible.',
      severity: 'high',
      status: 'in_progress',
      areaId: 'area-002-2',
      owner: 'Dana Kim',
      createdAt: '2024-03-05T11:00:00Z',
    },
    {
      id: 'issue-002-3',
      title: 'Online Checkout Error Reported',
      description: 'Customers reporting payment failures at checkout for orders over $200. Needs technical investigation.',
      severity: 'medium',
      status: 'open',
      areaId: 'area-002-3',
      owner: 'Chris Nguyen',
      createdAt: '2024-03-06T09:00:00Z',
    },
  ],
};

const brightlineDigitalOps: BusinessOperationsData = {
  businessId: 'biz-003',
  areas: [
    {
      id: 'area-003-1',
      name: 'Client Delivery',
      description: 'Project execution, deliverables, and client satisfaction',
      status: 'healthy',
      owner: 'Alex Rivera',
    },
    {
      id: 'area-003-2',
      name: 'Sales Pipeline',
      description: 'Lead generation, proposals, and new client acquisition',
      status: 'at_risk',
      owner: 'Alex Rivera',
    },
    {
      id: 'area-003-3',
      name: 'Team Coordination',
      description: 'Capacity planning, workload distribution, and internal alignment',
      status: 'at_risk',
      owner: 'Alex Rivera',
    },
    {
      id: 'area-003-4',
      name: 'Finance & Invoicing',
      description: 'Invoice tracking, revenue recognition, and expense management',
      status: 'healthy',
      owner: 'Alex Rivera',
    },
    {
      id: 'area-003-5',
      name: 'Marketing Ops',
      description: "Agency's own marketing, content, and inbound lead generation",
      status: 'healthy',
      owner: 'Alex Rivera',
    },
  ],
  recurringTasks: [
    {
      id: 'task-003-1',
      title: 'Client Check-ins',
      description: 'Weekly status calls with active clients to review progress and feedback',
      frequency: 'weekly',
      status: 'completed',
      nextDue: 'This Week',
      areaId: 'area-003-1',
      owner: 'Alex Rivera',
    },
    {
      id: 'task-003-2',
      title: 'Proposal Follow-ups',
      description: 'Follow up on outstanding proposals and move prospects through pipeline',
      frequency: 'weekly',
      status: 'in_progress',
      nextDue: 'Today',
      areaId: 'area-003-2',
      owner: 'Alex Rivera',
    },
    {
      id: 'task-003-3',
      title: 'Invoice Tracking Review',
      description: 'Check outstanding invoices, send reminders, and update cash flow forecast',
      frequency: 'biweekly',
      status: 'pending',
      nextDue: 'This Week',
      areaId: 'area-003-4',
      owner: 'Alex Rivera',
    },
    {
      id: 'task-003-4',
      title: 'Team Capacity Review',
      description: 'Review team utilization and redistribute workload if needed',
      frequency: 'weekly',
      status: 'pending',
      nextDue: 'This Week',
      areaId: 'area-003-3',
      owner: 'Alex Rivera',
    },
    {
      id: 'task-003-5',
      title: 'Support Queue Review',
      description: 'Process client requests, bug reports, and change requests',
      frequency: 'daily',
      status: 'in_progress',
      nextDue: 'Today',
      areaId: 'area-003-1',
      owner: 'Alex Rivera',
    },
    {
      id: 'task-003-6',
      title: 'Churn & Retention Review',
      description: 'Identify at-risk clients and prepare retention actions',
      frequency: 'monthly',
      status: 'pending',
      nextDue: 'This Month',
      areaId: 'area-003-2',
      owner: 'Alex Rivera',
    },
  ],
  issues: [
    {
      id: 'issue-003-1',
      title: 'Pipeline Conversion Rate Dropped',
      description: 'Trial-to-signed conversion dropped from 38% to 21% over last 6 weeks. Root cause unclear.',
      severity: 'high',
      status: 'open',
      areaId: 'area-003-2',
      owner: 'Alex Rivera',
      createdAt: '2024-03-02T10:00:00Z',
    },
    {
      id: 'issue-003-2',
      title: 'Key Deliverable Delayed — Client X',
      description: 'Website redesign for primary client is 10 days behind schedule due to feedback delays.',
      severity: 'medium',
      status: 'in_progress',
      areaId: 'area-003-1',
      owner: 'Alex Rivera',
      createdAt: '2024-03-04T14:00:00Z',
    },
    {
      id: 'issue-003-3',
      title: 'Overload on Two Senior Team Members',
      description: 'Two senior staff are at 130%+ capacity. Risk of burnout and quality degradation.',
      severity: 'high',
      status: 'open',
      areaId: 'area-003-3',
      owner: 'Alex Rivera',
      createdAt: '2024-03-05T09:00:00Z',
    },
  ],
};

export const mockOperationsData: BusinessOperationsData[] = [
  brewedAwakeningOps,
  apexThreadsOps,
  brightlineDigitalOps,
];
